language: generic
sudo: required  # whenever using docker, you need sudo
services:
  - docker

before_install:
  - docker build -t paulpatena/docker-react -f Dockerfile.dev .   # tag it so that travis can access img

scripts:
  - docker run -e CI=true paulpatena/docker-react npm run test