sudo: required  # whenever using docker, you need sudo
language: generic
services:
  - docker

before_install:
  - docker build -t paulpatena/docker-react -f Dockerfile.dev .   # tag it to easily access img

scripts:
  - docker run -e CI=true paulpatena/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-772544791412'
  bucket_path: 'docker-react'  # use the same value as your beanstalk application name
  on:
    branch: master  # deploy only when something is pushed to master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
